#FICHIER qui définit la configuration du déploiement vers Lambda 
#fonctionnement: 
# - sépcifie les détails de la fonction lambda (taille mémoire, temps exécution maximum, déclencheurs d'évènements)
# - prend en compte les configurations pour les dépendances, les rôles IAM et autres paramètres AWS
service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.4.8
  stage: dev
  region: eu-west-3

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: test-lambda
    handler: lambda.handler 
    description: test-lambda
    timeout: 5 #secondes
    memorySize: 128 #mb
    package: 
      patterns:
      - "!node_modules/**"
      - "!yarn.lock"
      - "!package-lock.json"
      - "!package.json"

