name : Deploying with Lambda 

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # pas compris ça 
      
      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'


